### ISSUE TITLE
Instalation tutorial

### ISSUE THREAD

**Issue by davirs** [steverobbins/Magento-Multi_Client#1]
Hi. This module should save my life!!! But I could not make it work properly..
Can you help me with steps to installation and configuration??
thank you!!!!!!!!!!!!!!!

**Comment by steverobbins** [comment]
Yeah, this has a ways to go before it's really ready for the community.  I only wanted to demonstrate the concept.  It's doing some pretty wacky things so it takes good working knowledge of Magento to get it running.

I have plans to build an installer, but in the mean time I can try to walk you through it.

Where exactly are you stuck?  Seeing any error messages?  Let's jump on [Gitter](https://gitter.im/steverobbins/Magento-Multi_Client) and discuss.

**Comment by assaka** [comment]
Hi steve,
Let me know when you are available, because i am also interested in the concept of having multiple clients on a single installation.
Greetings,
Hamid

**Comment by steverobbins** [comment]
Please see instructions in wiki

https://github.com/steverobbins/Magento-Multi_Client/wiki/Installation-Instructions-(Nginx)
